---
- hosts: all
  become: true

  pre_tasks:
    - name: vars
      include_vars: vars.yml

    - name: apt cache update & Upgrade
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: full
  tasks:

    - name: Install packages/prerequisites
      import_tasks: tasks/packages.yml

    - name: Install Docker
      import_tasks: tasks/docker.yml
    
    - name: Deploy pihole
      import_tasks: tasks/pihole.yml
      