---

- name: pihole docker deploy
  community.docker.docker_container:
    name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    volumes:
      - "./etc-pihole/:/etc/pihole/"
      - "./etc-dnsmasq.d/:/etc/dnsmasq.d/"
    env: 
      TZ: "{{ timezone }}"
      WEBPASSWORD: "{{ password }}"
      ServerIP: "{{ ansible_facts['default_ipv4']['address'] }}"
    dns_servers:
      - 127.0.0.1
      - 1.1.1.1
    restart_policy: unless-stopped
    network_mode: host
